FROM rust:1.76 AS builder
WORKDIR /app
COPY . .
RUN cargo build --release

FROM ubuntu:24.04
WORKDIR /app
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
COPY --from=builder /app/target/release/chargemap-proxy .
COPY config.toml .
EXPOSE 8082
CMD ["./chargemap-proxy"]
